FROM node:lts-alpine

ARG VITE_SUBNET_REGISTRATOR_CONTRACT_ADDRESS
ARG VITE_TOPOS_CORE_PROXY_CONTRACT_ADDRESS
ARG VITE_ERC20_MESSAGING_CONTRACT_ADDRESS
ARG VITE_TOPOS_SUBNET_ENDPOINT_REMOTE_DEFAULT
ARG VITE_TOPOS_SUBNET_ENDPOINT_CUSTOM_DEFAULT
ARG VITE_TCE_ENDPOINT_REMOTE_DEFAULT
ARG VITE_TCE_ENDPOINT_CUSTOM_DEFAULT

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY . ./

RUN npm run build

CMD npm run preview -- --port 80 --host 0.0.0.0
