name: Run build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest-16-core
    strategy:
      matrix:
        environment: [devnet-1, testnet-1]
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install npm packages
        run: npm ci

      - name: Run build
        run: npm run build
        env:
          VITE_ERC20_MESSAGING_CONTRACT_ADDRESS: ${{ vars.ERC20_MESSAGING_CONTRACT_ADDRESS }}
          VITE_SUBNET_REGISTRATOR_CONTRACT_ADDRESS: ${{ vars.SUBNET_REGISTRATOR_CONTRACT_ADDRESS }}
          VITE_TOPOS_CORE_PROXY_CONTRACT_ADDRESS: ${{ vars.TOPOS_CORE_PROXY_CONTRACT_ADDRESS }}
          VITE_TOPOS_SUBNET_ENDPOINT_REMOTE_DEFAULT: ${{ vars.TOPOS_SUBNET_ENDPOINT_REMOTE_DEFAULT }}
          VITE_TOPOS_SUBNET_ENDPOINT_CUSTOM_DEFAULT: ${{ vars.TOPOS_SUBNET_ENDPOINT_CUSTOM_DEFAULT }}
          VITE_TCE_ENDPOINT_REMOTE_DEFAULT: ${{ vars.TCE_ENDPOINT_REMOTE_DEFAULT }}
          VITE_TCE_ENDPOINT_CUSTOM_DEFAULT: ${{ vars.TCE_ENDPOINT_CUSTOM_DEFAULT }}
